phishsense/modelqueue/urls.py
from django.conf.urls import url

from . import views, loginviews

app_name = 'modelqueue'

urlpatterns = [
    url(r'^$', views.IndexPageView.as_view(), name='index'),
    url(r'^index/$', views.IndexPageView.as_view(), name='index'),
    url(r'^status/(?P<uuid>[0-9a-z-]+)/$', views.check_status, name='check_status'),
    url(r'^signin/$', loginviews.signin, name='signin'),

    # URLs for various stages of finding verdict - Django way
    url(r'^crawl_url/$', views.crawl_url, name='crawl_url'),
    url(r'^extract_features/$', views.extract_features, name='extract_features'),
    url(r'^query_model/$', views.query_model, name='query_model'),
    url(r'^show_result/$', views.show_result, name='show_result'),

    # URLs enabling offloading tasks to caller (enabling REST APIs)
    url(r'^api/v1/request_task/$', views.request_task, name='request_task'),
    url(r'^api/v1/request_task_bulk/(?P<count>[0-9]+)/$', views.request_task_bulk, name='request_task_bulk'),
    url(r'^api/v1/respond_task_results/$', views.respond_task_results, name='respond_task_results'),
    url(r'^api/v1/post_single_analysisurl/$', views.post_single_analysisurl, name='post_single_analysisurl'),
    url(r'^api/v1/get_single_verdict/$', views.get_single_verdict, name='get_single_verdict'),
]

phishsense/phishsense/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from modelqueue import views as modelqueueviews

from django.contrib.auth.models import User
from rest_framework import routers

from modelqueue.views import UserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


urlpatterns = [
    url(r'^phishsense/', include('modelqueue.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', modelqueueviews.IndexPageView.as_view(), name='index'),

    # Django Rest framework
    url(r'^drf', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

phishsense/modelqueue/models.py
import datetime
import uuid

from django.db import models

from licenseapp.models import UserLicenseUsage


class UserLicenseVerdictMap(models.Model):
    """
    Mapping Users to Verdict
    """
    userlicenseusage = models.ForeignKey(UserLicenseUsage, related_name='%(app_label)s_%(class)s_related',
                                verbose_name='User License Usage FK', help_text='User License Usage')
    verdict = models.ForeignKey("PhishVerdictModel", related_name='%(app_label)s_%(class)s_related',
                                verbose_name='Verdict FK', help_text='Verdict FK')


class InvestigateUrlModel(models.Model):
    """
    Model to store unique URLs that are requested for verifying whether they are malicious.
    """
    analysis_url = models.URLField()
    url_sha = models.CharField(unique=True, blank=True, null=True, max_length=40)
    created_date = models.DateField(default=datetime.date.today, help_text='Created Date')
    modified_date = models.DateField(default=datetime.date.today, help_text='Modified Date')

    def __unicode__(self):
        return self.analysis_url

    class Meta:
        verbose_name = 'Investigate URL'
        verbose_name_plural = 'Investigate URLs'


class PhishVerdictModel(models.Model):
    """
    Each run of the analysis verdict for a suspect URL.
    """

    ANALYSIS_STAGES = (
                       (0, 'New|Waiting'),
                       (1, 'Crawl'),
                       (2, 'Extraction'),
                       (3, 'Query Model'),
                       (4, 'Complete'),
                       (5, 'Offloaded (Single)'),
                       (6, 'Offloaded (Bulk)'),
    )

    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    answer = models.FloatField(blank=True, null=True)
    features = models.TextField(blank=True, null=True)

    internal_download_path = models.FileField(upload_to='uploads/%Y/%m/%d', null=True, blank=True)

    investigate_url = models.ForeignKey("InvestigateUrlModel", related_name='%(app_label)s_%(class)s_related',
                                        verbose_name='Investigate Url FK', help_text='Investigate Url')

    comments = models.TextField(null=True, blank=True, help_text="Any Comments, Notes")
    analysis_stage = models.IntegerField(choices=ANALYSIS_STAGES, default=0,
                                            help_text="Verdict Analysis Stage")
    
    created_date  = models.DateField(null=True, blank=True, default=datetime.date.today, help_text='Created Date')
    modified_date  = models.DateField(null=True, blank=True, default=datetime.date.today, help_text='Modified Date')

    def __unicode__(self):
        return self.investigate_url.analysis_url

    class Meta:
        verbose_name = 'Verdict'
        verbose_name_plural = 'Verdicts'

    def is_phishing(self):
        # Decide whether the verdict is that the URL is malicious
        return 1 <= self.answer <= 0
    is_phishing.admin_order_field = 'answer'
    is_phishing.boolean = True
    is_phishing.short_description = 'Is Phishing?'

    def analysis_stage_text(self):
        return PhishVerdictModel.ANALYSIS_STAGES[self.analysis_stage][1]
    is_phishing.admin_order_field = 'stage'
    is_phishing.short_description = 'Analysis Stage'


class OffloadTasksModel(models.Model):
    phish_verdict_model = models.ForeignKey("PhishVerdictModel", related_name='%(app_label)s_%(class)s_related',
                                        verbose_name='PhishVerdictModel FK', help_text='PhishVerdictModel')
    time_sha = models.CharField(unique=True, blank=True, null=True, max_length=40)
    created_date  = models.DateField(null=True, blank=True, default=datetime.date.today, help_text='Created Date')
    modified_date  = models.DateField(null=True, blank=True, default=datetime.date.today, help_text='Modified Date')

    def _get_analysis_url(self):
        return self.phish_verdict_model.investigate_url.analysis_url
    _analysis_url = property(_get_analysis_url)

    def _get_uid(self):
        return str(self.phish_verdict_model.unique_id)
    _uid = property(_get_uid)

phishsense/modelqueue/forms.py
from django import forms

class URLForm(forms.Form):
	analysis_url = forms.URLField(label='Analysis URL', required=True)

phishsense/modelqueue/views.py
import simplejson
import hashlib
import time

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views.generic import FormView
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.conf import settings
from django.http import HttpResponseBadRequest

from .forms import URLForm
from .models import InvestigateUrlModel, PhishVerdictModel, OffloadTasksModel
from .modelqueue_utils import ViewsHelper
from rest_framework import viewsets, status

from .serializers import UserSerializer
from load_commonutils import get_ts_instance

v_helper = ViewsHelper()


class IndexPageView(FormView):
    template_name = 'modelqueue/index.html'
    form_class = URLForm

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ipaddress = x_forwarded_for.split(',')[-1].strip()
        else:
            ipaddress = self.request.META.get('REMOTE_ADDR')
        context['layout'] = self.request.GET.get('layout', 'vertical')
        context['ipaddress'] = ipaddress
        context['user'] = self.request.user
        context['UI_PROJECT_TITLE'] = settings.UI_PROJECT_TITLE
        return context

    def post(self, request, *args, **kwargs):
        form = URLForm(request.POST)
        if form.is_valid():
            analysis_url = form.cleaned_data['analysis_url']
            print "analysis_url : ", analysis_url
            pvm = v_helper.start_analysis(analysis_url)
            context = {'pvm': pvm }
            context['UI_PROJECT_TITLE'] = settings.UI_PROJECT_TITLE
            return render(request, 'modelqueue/resultpage.html', context)
        else:
            # TODO: Handle here for invalid cases
            print "invalid"
        return HttpResponse("Ok")


def check_status(request, uuid):
    pvm = get_object_or_404(PhishVerdictModel, unique_id=uuid)
    if pvm.analysis_stage == 0:
        crawl_url(request)
        time.sleep(0.1)
        extract_features(request)
        time.sleep(0.1)
        query_model(request)
        time.sleep(0.1)
        show_result(request)
        time.sleep(0.1)
    elif pvm.analysis_stage == 1:
        extract_features(request)
        time.sleep(0.1)
        query_model(request)
        time.sleep(0.1)
        show_result(request)
        time.sleep(0.1)
    elif pvm.analysis_stage == 2:
        query_model(request)
        time.sleep(0.1)
        show_result(request)
        time.sleep(0.1)
    elif pvm.analysis_stage == 3:
        show_result(request)
        time.sleep(0.1)
    else:
        # TODO: What should be the default action?
        pass

    pvm = get_object_or_404(PhishVerdictModel, unique_id=uuid)
    context = {'pvm': pvm }
    context['UI_PROJECT_TITLE'] = settings.UI_PROJECT_TITLE
    return render(request, 'modelqueue/resultpage.html', context)


def crawl_url(request):
    pending_crawling = PhishVerdictModel.objects.filter(analysis_stage=0)
    for each_pending_url in pending_crawling:
        v_helper.crawl_page(each_pending_url)
    # TODO: Consider appropriate response type
    return HttpResponse("Ok")


def extract_features(request):
    pending_feature_extraction = PhishVerdictModel.objects.filter(analysis_stage=1)
    for each_pending_feature_extraction in pending_feature_extraction:
        v_helper.extract_features(each_pending_feature_extraction)
    # TODO: Consider appropriate response type
    return HttpResponse("Ok")


def query_model(request):
    pending_querying_model = PhishVerdictModel.objects.filter(analysis_stage=2)
    for each_pending in pending_querying_model:
        v_helper.query_model(each_pending)
    # TODO: Consider appropriate response type
    return HttpResponse("Ok")


def show_result(request):
    pending_for_results = PhishVerdictModel.objects.filter(analysis_stage=3)
    for each_pending in pending_for_results:
        v_helper.provide_result(each_pending)
    # TODO: Consider appropriate response type
    return HttpResponse("Ok")


def request_task(request):
    """Returns 1 pending request for offline processing"""
    pending_crawling = PhishVerdictModel.objects.filter(analysis_stage=0)[:1]
    task_dict = {}
    for each_pending in pending_crawling:
        time_sha = hashlib.sha1(get_ts_instance()).hexdigest()
        otm = OffloadTasksModel(phish_verdict_model=each_pending, time_sha=time_sha)
        otm.save()
#         each_pending.each_pending = 5
#         each_pending.save()
        task_dict[otm._uid] = {}
        task_dict[otm._uid]['sha'] = time_sha
        task_dict[otm._uid]['analysis_url'] = otm._analysis_url
    print "request_task: ", task_dict
    jresponse = simplejson.dumps(task_dict)
    return HttpResponse(jresponse, content_type='application/json')


def request_task_bulk(request, count):
    pending_crawling = PhishVerdictModel.objects.filter(analysis_stage=0)[:count]
    task_dict = {}
    for each_pending in pending_crawling:
        time_sha = hashlib.sha1(get_ts_instance()).hexdigest()
        otm = OffloadTasksModel(phish_verdict_model=each_pending, time_sha=time_sha)
        otm.save()
#         each_pending.each_pending = 5
#         each_pending.save()
        task_dict[otm._uid] = {}
        task_dict[otm._uid]['sha'] = time_sha
        task_dict[otm._uid]['analysis_url'] = otm._analysis_url
    print "request_task_bulk: ",task_dict
    jresponse = simplejson.dumps(task_dict)
    return HttpResponse(jresponse, content_type='application/json')


@csrf_exempt
def respond_task_results(request):
    # TODO: Lets comply with csrf
    if request.method=='POST':
        received_json_data = simplejson.loads(request.body)
        print "received_json_data: ",received_json_data
        if v_helper.is_response_valid(received_json_data):
            # Update the Model based on the values recieved
            status, message = v_helper.update_from_api_response(received_json_data)
            if status:
                jresponse = simplejson.dumps({'message': message, 'status': status})
                return HttpResponse(jresponse, content_type='application/json')
            else:
                return HttpResponseBadRequest()

    return HttpResponseBadRequest()


@csrf_exempt
def post_single_analysisurl(request):
    # TODO: Lets comply with csrf
    if request.method=='POST':
        received_json_data = simplejson.loads(request.body)
        print "received_json_data: ",received_json_data
        if v_helper.is_analysisurl_request_valid(received_json_data):
            pvm = v_helper.start_analysis(received_json_data['analysis_url'])
            jresponse = simplejson.dumps({'uid': str(pvm.unique_id)})
            print 'jresponse: ',jresponse
            return HttpResponse(jresponse, content_type='application/json')
    return HttpResponseBadRequest()

@csrf_exempt
def get_single_verdict(request):
    # TODO: Lets comply with csrf
    if request.method=='POST':
        received_json_data = simplejson.loads(request.body)
        print "received_json_data: ",received_json_data
        status, msg = v_helper.process_get_verdict(received_json_data)
        print 'status, msg: ',status, msg
        if status:
            jresponse = simplejson.dumps({'uid': received_json_data['uid'], 'verdict':  msg })
            print 'jresponse: ',jresponse
            return HttpResponse(jresponse, content_type='application/json')
    return HttpResponseBadRequest()


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

phishsense/modelqueue/templates/modelqueue/base.html
{% extends "modelqueue/bs_dash.html" %}

{% block projectname %}<a class="navbar-brand" href="{% url 'modelqueue:index' %}">{{ UI_PROJECT_TITLE }}</a>{% endblock projectname %}

{% block navbar %}
    {% if user.username %}
        <div id="navbar" class="navbar-right">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Logout</a></li>
                    <li class="dropdown-header">Account Settings</li>
                    <li><a href="#">Profile</a></li>
                  </ul>
                </li>
                <li>...</li>
            </ul>
    {% else %}
      <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
        <button type="submit" class="btn btn-info">Register</button>
      </form>
    {% endif %}
</div><!--/.navbar-collapse -->
{% endblock navbar %}

{% block appsearch %}{% endblock appsearch %}

{% block sidenavbar %}
{% endblock sidenavbar %}

{% block pageheader %}
<h1 class="page-header">{{ UI_PROJECT_TITLE }}</h1>
{% endblock pageheader %}

phishsense/modelqueue/templates/modelqueue/bs_dash.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'modelqueue/bootstrap-3.3.6-dist/images/favicon.ico' %}">

    {% block title %}<title>Dashboard Template for Bootstrap</title>{% endblock title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'modelqueue/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'modelqueue/bootstrap-3.3.6-dist/assets/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'modelqueue/bootstrap-3.3.6-dist/css/dashboard.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'modelqueue/bootstrap-3.3.6-dist/assets/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Load Custom CSS and JS -->
    <link href="{% static 'modelqueue/custom.css' %}" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block projectname %}<a class="navbar-brand" href="#">Project name</a>{% endblock projectname %}
        </div>
        {% block navbar %}
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          {% endblock navbar %}
          {% block appsearch %}
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
          {% endblock appsearch %}
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
      {% block sidenavbar %}
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
      {% endblock sidenavbar %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% block pageheader %}
          <h1 class="page-header">Dashboard</h1>
        {% endblock pageheader %}

        {% block content %}
          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
          {% endblock content %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'modelqueue/jquery-1.11.3/jquery.min.js' %}"></script>
    
    <script src="{% static 'modelqueue/bootstrap-3.3.6-dist/js/bootstrap.min.js' %}"></script>
    
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'modelqueue/bootstrap-3.3.6-dist/assets/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'modelqueue/bootstrap-3.3.6-dist/assets/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

phishsense/modelqueue/templates/modelqueue/index.html
{% extends "modelqueue/base.html" %}

{% load bootstrap3 %}

{% block title %}<title>{{ UI_PROJECT_TITLE }} index</title>{% endblock title %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">Submit a URL</div>
  <div class="panel-body">
    <form action="." role="form" method="post" class="form-vertical">
        {% csrf_token %}
        {% bootstrap_form form layout=layout %}
        {% buttons submit='Submit' %}{% endbuttons %}
    </form>
    </div>
</div>
<div>
    <span class="index-ipaddress-span">{{ ipaddress }}</span>
</div>
{% endblock content %}

phishsense/modelqueue/templates/modelqueue/resultpage.html
{% extends "modelqueue/base.html" %}

{% load bootstrap3 %}

{% block title %}<title>{{ UI_PROJECT_TITLE }} Result Page</title>{% endblock title %}

{% block content %}
<div class="panel panel-default">
    <p>Result Page</p>
    <p>UID: {{ pvm.unique_id }}</p>
    <p>Status: {% if pvm.analysis_stage == 4 %}Completed{% else %}Processing{% endif %}</p>
    {% if pvm.analysis_stage == 4 %}
        <p>Result: Clean | Suspect
    {% else %}
        <h3><span class="label label-info"><a href="{% url 'modelqueue:check_status' pvm.unique_id %}">Check Status</a></span></h3>
    {% endif %}  
</div>
{% endblock content %}

phishsense/modelqueue/templates/modelqueue/signin.html
{% extends "modelqueue/base.html" %}

{% block title %}<title>{{ UI_PROJECT_TITLE }} SignIn</title>{% endblock title %}

{% block pageheader %}
<h1 class="page-header">Sign In (TODO)</h1>
{% endblock pageheader %}

{% block navbar %}
{% endblock navbar %}